//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func sumOfEvenFibonacciNums(limit: Int) -> Int {
    var fibonacciArray = [1, 2]
    while fibonacciArray.last! < limit {
        let nextNumber = fibonacciArray[fibonacciArray.count - 2] + fibonacciArray.last!
        fibonacciArray.append(nextNumber)
    }
    fibonacciArray.removeLast()
    return fibonacciArray.filter {
        $0 % 2 == 0
    }.reduce(0, +)
}

print(sumOfEvenFibonacciNums(limit: 90))
print(sumOfEvenFibonacciNums(limit: 4000000))
